# Oasis Infobyte Internship

# Task 1: Iris Flower Classification

## Internship Domain
**Data Science**

---

## Project Overview

The Iris Flower Classification project is one of the most fundamental machine learning classification problems. The objective is to build a machine learning model capable of predicting the species of an Iris flower based on its physical characteristics.

The dataset contains measurements of different Iris flowers including:

- Sepal Length
- Sepal Width
- Petal Length
- Petal Width

Using these measurements, our model will classify flowers into one of three species:

- Iris Setosa
- Iris Versicolor
- Iris Virginica

---

## Objectives

- Understand the dataset
- Perform Data Cleaning
- Perform Exploratory Data Analysis (EDA)
- Visualize important relationships
- Build Machine Learning Models
- Compare model performances
- Select the best model
- Evaluate the model
- Save the trained model

---

## Technologies Used

- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn
- Scikit-Learn
- Joblib

---

## Author

**Anirban Garai**

Oasis Infobyte Internship

In [1]:
# ==========================================
# Import Required Libraries
# ==========================================

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris

import warnings
warnings.filterwarnings("ignore")

# Importing Libraries

Before starting any machine learning project, it is essential to import the required Python libraries.

### NumPy
Used for numerical computations.

### Pandas
Used for loading and manipulating datasets.

### Matplotlib
Used for plotting graphs.

### Seaborn
Used for attractive statistical visualizations.

### Scikit-Learn
Provides built-in datasets and machine learning algorithms.

In [2]:
# Set Plotting Style

sns.set_style("whitegrid")

plt.rcParams["figure.figsize"] = (8,5)

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

# Loading the Dataset

For this project, we are using the famous Iris dataset available in Scikit-Learn.

The dataset contains 150 flower samples belonging to three species.

Each flower has four numerical features.

The target column represents the flower species.

In [3]:
# Load Iris Dataset

iris = load_iris()

print(type(iris))

<class 'sklearn.utils._bunch.Bunch'>

# Understanding Dataset Structure

The Iris dataset is stored as a Python dictionary.

Let's inspect the available keys.

In [4]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

# Dataset Description

The dataset contains:

- Feature Names
- Target Names
- Description
- Data
- Labels

Let's read each one.

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

# Feature Names

These are the four measurements collected from every flower.

In [6]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

# Target Classes

The Iris dataset contains three flower species.

In [7]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']

# Creating a DataFrame

Machine Learning projects are easier to analyze using a Pandas DataFrame.

In [8]:
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df['Species'] = iris.target

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

# Replacing Numerical Labels

Currently the species column contains:

- 0
- 1
- 2

Let's replace them with actual flower names.

In [9]:
species_names = {
    0:'Setosa',
    1:'Versicolor',
    2:'Virginica'
}

df['Species'] = df['Species'].map(species_names)

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
0,5.1,3.5,1.4,0.2,Setosa
1,4.9,3.0,1.4,0.2,Setosa
2,4.7,3.2,1.3,0.2,Setosa
3,4.6,3.1,1.5,0.2,Setosa
4,5.0,3.6,1.4,0.2,Setosa

# Dataset Overview

Let's understand the overall structure of our dataset.

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   Species            150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

# Display First 10 Records

Viewing the first few rows helps verify that the dataset has loaded correctly.

In [11]:
df.head(10)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
0,5.1,3.5,1.4,0.2,Setosa
1,4.9,3.0,1.4,0.2,Setosa
2,4.7,3.2,1.3,0.2,Setosa
3,4.6,3.1,1.5,0.2,Setosa
4,5.0,3.6,1.4,0.2,Setosa
5,5.4,3.9,1.7,0.4,Setosa
6,4.6,3.4,1.4,0.3,Setosa
7,5.0,3.4,1.5,0.2,Setosa
8,4.4,2.9,1.4,0.2,Setosa
9,4.9,3.1,1.5,0.1,Setosa

# Display Last 10 Records

Sometimes checking the last few records helps ensure data consistency.

In [12]:
df.tail(10)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
140,6.7,3.1,5.6,2.4,Virginica
141,6.9,3.1,5.1,2.3,Virginica
142,5.8,2.7,5.1,1.9,Virginica
143,6.8,3.2,5.9,2.3,Virginica
144,6.7,3.3,5.7,2.5,Virginica
145,6.7,3.0,5.2,2.3,Virginica
146,6.3,2.5,5.0,1.9,Virginica
147,6.5,3.0,5.2,2.0,Virginica
148,6.2,3.4,5.4,2.3,Virginica
149,5.9,3.0,5.1,1.8,Virginica

# Shape of Dataset

The shape tells us:

- Number of Rows
- Number of Columns

In [13]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 150
Columns : 5

# Column Names

Let's display all columns present in the dataset.

In [14]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'Species'],
      dtype='object')

# Data Types

Checking data types is an important preprocessing step.

In [15]:
df.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
Species               object
dtype: object

# Summary Statistics

The describe() function provides:

- Mean
- Standard Deviation
- Minimum
- Maximum
- Quartiles

This gives us a statistical overview of the dataset.

In [16]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000